#!/usr/bin/env bash
# Regenerate .claude/agents/.known-hashes — the provenance manifest install.sh uses
# to tell its OWN prior output apart from a genuine user-authored agent override.
#
# Why this exists: install.sh deploys canonical agents to ~/.claude/agents/.pickle-managed/,
# but installs predating the overlay migration (commit 0be35568, 2026-04-30) wrote them
# straight into ~/.claude/agents/. The loader (services/agent-md-loader.ts) gives a
# top-level file precedence over .pickle-managed, so leftover installer output from an
# older version silently outranks every future update.
#
# Distinguishing those two cases is a question about CONTENT PROVENANCE, not file
# metadata: a file whose bytes the installer has shipped at some point is installer
# output; a file whose bytes it never shipped is the user's. This manifest records
# every version of every agent the installer has ever shipped, so that question is
# decidable offline, on any platform, without git at install time.
#
# Usage: bash extension/scripts/gen-agent-known-hashes.sh
# Run after changing any file under .claude/agents/ and commit the result.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"

AGENTS_SUBDIR=".claude/agents"
OUT="$AGENTS_SUBDIR/.known-hashes"

if ! command -v git >/dev/null 2>&1; then
  echo "gen-agent-known-hashes: git is required" >&2
  exit 1
fi

sha256_stdin() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum | awk '{print $1}'
  elif command -v shasum >/dev/null 2>&1; then
    shasum -a 256 | awk '{print $1}'
  else
    echo "gen-agent-known-hashes: no sha256sum/shasum available" >&2
    exit 1
  fi
}

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

# Every path that has ever existed under .claude/agents/*.md, across all refs — a
# renamed or deleted agent may still be sitting in a user's ~/.claude/agents/.
paths="$(
  {
    git log --all --pretty=format: --name-only -- "$AGENTS_SUBDIR" 2>/dev/null || true
    ls -1 "$AGENTS_SUBDIR"/*.md 2>/dev/null || true
  } | grep -E "^${AGENTS_SUBDIR}/[^/]+\.md$" | sort -u
)"

for p in $paths; do
  agent_file="$(basename "$p")"
  # Every historical revision of this path, plus the working-tree copy.
  for rev in $(git rev-list --all -- "$p" 2>/dev/null); do
    blob_hash="$(git cat-file blob "$rev:$p" 2>/dev/null | sha256_stdin || true)"
    [ -n "$blob_hash" ] && echo "$agent_file $blob_hash" >> "$tmp"
  done
  if [ -f "$p" ]; then
    echo "$agent_file $(sha256_stdin < "$p")" >> "$tmp"
  fi
done

{
  echo "# <agent-filename> <sha256-of-shipped-content>"
  echo "# Generated by extension/scripts/gen-agent-known-hashes.sh — do not hand-edit."
  echo "# Every version of every agent install.sh has ever shipped. A legacy top-level"
  echo "# agent whose content hash appears here is installer output and is migrated to"
  echo "# .pickle-managed/; anything else is a user override and is preserved."
  sort -u "$tmp"
} > "$OUT"

echo "gen-agent-known-hashes: wrote $OUT ($(grep -cv '^#' "$OUT") shipped versions across $(echo "$paths" | wc -w | tr -d ' ') agent files)"
